# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13f96214b47feecb4a864b77a9c321c15d938d4a56d5536d8958a5933c260b0849ed134303b5bc2ed7abbd93253606fd05fc0be47acb6d31f64d79e8ec18d615

test:
  secret_key_base: 3d5b6df2305c3bf9f5d01b533f98073c8a8e1384bec3eef5dcf54ccd785ba573fec080febf3ec226169f1774420b35e57160be571739c3d35509c7678a1acd3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
